apiVersion: v1
kind: Service
metadata:
  name: api-compras
  labels:
    run: api-compras
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      nodePort: 30002
  type: NodePort
  selector:
    app: api-compras
